version: '3.3'
services:
  db:
    image: mysql/mysql-server:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'erp.aero.db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3307:3306'
    expose:
      - '3306'
    volumes:
      - erp-aero-db:/var/lib/mysql

  redis:
    container_name: redis
    image: redis:7.0.10-alpine
    # command: redis-server /usr/local/etc/redis/redis.conf --requirepass mypassword
    restart: always
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - cache:/data

volumes:
  erp-aero-db:
  cache: